# Generated by Django 5.0.3 on 2024-05-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0003_remove_mascota_edad_mascota_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.TextField()),
                ('indicaciones', models.TextField()),
                ('veterinario', models.CharField(max_length=100)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'db_table': 'consultas',
            },
        ),
    ]
