# Generated by Django 5.0.3 on 2024-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_rename_diagnostico_consulta_indicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='indicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
