# Generated by Django 5.0.3 on 2024-05-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_indicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='fecha',
            new_name='fecha_consulta',
        ),
    ]
