# Generated by Django 5.0.3 on 2024-08-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
        ('recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='especies.especie'),
        ),
    ]
