# Generated by Django 5.0.3 on 2024-03-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='noticias',
        ),
    ]
