# Generated by Django 5.0.3 on 2024-03-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_options_alter_noticia_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
