# Generated by Django 5.0.3 on 2024-06-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia_id', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('usuario_id', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria_noticias',
            },
        ),
    ]
