# Generated by Django 5.0.3 on 2024-05-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0003_remove_mascota_edad_mascota_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=100)),
                ('dosis_aplicada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vacunacion', models.DateField()),
                ('fecha_proxima_vacunacion', models.DateField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'db_table': 'vacunaciones',
            },
        ),
    ]
