# Generated by Django 5.0.3 on 2024-05-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacunaciones', '0001_initial'),
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunacion',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.vacuna'),
        ),
    ]
