# Generated by Django 5.0.3 on 2024-05-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='fecha_proxima_vacunacion',
        ),
    ]
