# Generated by Django 5.0.3 on 2024-03-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
