# Generated by Django 5.0.3 on 2024-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
