# Generated by Django 5.0.3 on 2024-07-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20240630_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, null=True)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('grupo_usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria_usuarios',
            },
        ),
    ]
